SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ENDERECO` (
  `id` INT NOT NULL,
  `logradouro` VARCHAR(256) NULL,
  `numero` INT NULL,
  `cep` INT NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(30) NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`PESSOA` (
  `id` INT NOT NULL,
  `nome` VARCHAR(256) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `ENDERECO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PESSOA_ENDERECO1_idx` (`ENDERECO_id` ASC) VISIBLE,
  CONSTRAINT `fk_PESSOA_ENDERECO1`
    FOREIGN KEY (`ENDERECO_id`)
    REFERENCES `mydb`.`ENDERECO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE_TIPO` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE` (
  `id` INT NOT NULL,
  `numero` INT NULL,
  `ddd` INT NULL,
  `TELEFONE_TIPO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TELEFONE_TELEFONE_TIPO1_idx` (`TELEFONE_TIPO_id` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONE_TELEFONE_TIPO1`
    FOREIGN KEY (`TELEFONE_TIPO_id`)
    REFERENCES `mydb`.`TELEFONE_TIPO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`PESSOA_TELEFONE` (
  `PESSOA_id` INT NOT NULL,
  `TELEFONE_id` INT NOT NULL,
  INDEX `fk_PESSOA_TELEFONE_PESSOA_idx` (`PESSOA_id` ASC) VISIBLE,
  INDEX `fk_PESSOA_TELEFONE_TELEFONE1_idx` (`TELEFONE_id` ASC) VISIBLE,
  PRIMARY KEY (`PESSOA_id`, `TELEFONE_id`),
  CONSTRAINT `fk_PESSOA_TELEFONE_PESSOA`
    FOREIGN KEY (`PESSOA_id`)
    REFERENCES `mydb`.`PESSOA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_TELEFONE_TELEFONE1`
    FOREIGN KEY (`TELEFONE_id`)
    REFERENCES `mydb`.`TELEFONE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
